language: perl
sudo: false
perl:
  - "5.26"
  - "5.20"
  - "5.16"
  - "5.14"
  - "5.10"
addons:
  mysql: "5.7"
before_script:
  - mysql -e 'create database myapp_test default character set utf8 default collate utf8_general_ci;'
env:
  - "HARNESS_OPTIONS=j3 TEST_POD=1 TEST_PUBSUB=1 TEST_FOR=500 TEST_ONLINE=mysql://root@/myapp_test"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
notifications:
  email: false
